server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

  # JWT Secret key
jwt:
  secret: "bHVja3lkcm9wc2VjcmV0YWNjZXNzdG9rZW5sdWNreWRyb3BzZWNyZXRhY2Nlc3N0b2tlbg=="
  expiration: 3000 #분

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    doc-expansion: none